In [1]:
# day 3. Pandas

In [2]:
pip install pydataset

Collecting pydataset
  Downloading pydataset-0.2.0.tar.gz (15.9 MB)
     ---------------------------------------- 0.0/15.9 MB ? eta -:--:--
     ---------------------------------------- 0.1/15.9 MB 1.1 MB/s eta 0:00:15
      --------------------------------------- 0.2/15.9 MB 2.3 MB/s eta 0:00:07
      --------------------------------------- 0.3/15.9 MB 2.7 MB/s eta 0:00:06
     - -------------------------------------- 0.4/15.9 MB 2.8 MB/s eta 0:00:06
     - -------------------------------------- 0.7/15.9 MB 2.9 MB/s eta 0:00:06
     - -------------------------------------- 0.8/15.9 MB 2.7 MB/s eta 0:00:06
     -- ------------------------------------- 1.0/15.9 MB 3.1 MB/s eta 0:00:05
     -- ------------------------------------- 1.1/15.9 MB 3.0 MB/s eta 0:00:05
     --- ------------------------------------ 1.4/15.9 MB 3.3 MB/s eta 0:00:05
     --- ------------------------------------ 1.6/15.9 MB 3.5 MB/s eta 0:00:05
     ---- ----------------------------------- 1.7/15.9 MB 3.4 MB/s eta 0:00:05
     ---- ----------------------------------- 1.9/15.9 MB 3.5 MB/s eta 0:00:04
     ----- ---------------------------------- 2.1/15.9 MB 3.4 MB/s eta 0:00:05
     ----- ---------------------------------- 2.2/15.9 MB 3.3 MB/s eta 0:00:05
     ----- ---------------------------------- 2.3/15.9 MB 3.3 MB/s eta 0:00:05
     ------ --------------------------------- 2.6/15.9 MB 3.5 MB/s eta 0:00:04
     ------ --------------------------------- 2.8/15.9 MB 3.5 MB/s eta 0:00:04
     ------- -------------------------------- 3.1/15.9 MB 3.7 MB/s eta 0:00:04
     -------- ------------------------------- 3.2/15.9 MB 3.6 MB/s eta 0:00:04
     -------- ------------------------------- 3.4/15.9 MB 3.6 MB/s eta 0:00:04
     -------- ------------------------------- 3.6/15.9 MB 3.8 MB/s eta 0:00:04
     --------- ------------------------------ 3.7/15.9 MB 3.6 MB/s eta 0:00:04
     --------- ------------------------------ 4.0/15.9 MB 3.7 MB/s eta 0:00:04
     ---------- ----------------------------- 4.0/15.9 MB 3.6 MB/s eta 0:00:04
     ---------- ----------------------------- 4.3/15.9 MB 3.7 MB/s eta 0:00:04
     ----------- ---------------------------- 4.4/15.9 MB 3.6 MB/s eta 0:00:04
     ----------- ---------------------------- 4.7/15.9 MB 3.7 MB/s eta 0:00:04
     ------------ --------------------------- 4.9/15.9 MB 3.7 MB/s eta 0:00:04
     ------------ --------------------------- 5.1/15.9 MB 3.8 MB/s eta 0:00:03
     ------------- -------------------------- 5.3/15.9 MB 3.8 MB/s eta 0:00:03
     ------------- -------------------------- 5.4/15.9 MB 3.7 MB/s eta 0:00:03
     ------------- -------------------------- 5.6/15.9 MB 3.7 MB/s eta 0:00:03
     -------------- ------------------------- 5.9/15.9 MB 3.8 MB/s eta 0:00:03
     --------------- ------------------------ 6.1/15.9 MB 3.8 MB/s eta 0:00:03
     ---------------- ----------------------- 6.4/15.9 MB 3.9 MB/s eta 0:00:03
     ---------------- ----------------------- 6.7/15.9 MB 4.0 MB/s eta 0:00:03
     ----------------- ---------------------- 6.9/15.9 MB 4.0 MB/s eta 0:00:03
     ----------------- ---------------------- 7.0/15.9 MB 4.0 MB/s eta 0:00:03
     ------------------ --------------------- 7.3/15.9 MB 4.0 MB/s eta 0:00:03
     ------------------- -------------------- 7.6/15.9 MB 4.1 MB/s eta 0:00:03
     ------------------- -------------------- 7.9/15.9 MB 4.1 MB/s eta 0:00:02
     -------------------- ------------------- 8.0/15.9 MB 4.1 MB/s eta 0:00:02
     -------------------- ------------------- 8.2/15.9 MB 4.1 MB/s eta 0:00:02
     -------------------- ------------------- 8.3/15.9 MB 4.0 MB/s eta 0:00:02
     --------------------- ------------------ 8.5/15.9 MB 4.0 MB/s eta 0:00:02
     --------------------- ------------------ 8.7/15.9 MB 4.0 MB/s eta 0:00:02
     ---------------------- ----------------- 8.9/15.9 MB 4.0 MB/s eta 0:00:02
     ---------------------- ----------------- 9.0/15.9 MB 4.0 MB/s eta 0:00:02
     ----------------------- ---------------- 9.2/15.9 MB 4.0 MB/s eta 0:00:02
     ----------------------- ---------------- 9.5/15.9 MB 4.0 MB/s eta 0:00:02
     ------------------------ --------------- 9.6/15.9 MB 4.0 MB/s eta 0:00:02
     ------------------------ --------------- 10.0/15.9 MB 4.1 MB/s eta 0:00:02
     ------------------------- -------------- 10.1/15.9 MB 4.1 MB/s eta 0:00:02
     -------------------------- ------------- 10.4/15.9 MB 4.1 MB/s eta 0:00:02
     -------------------------- ------------- 10.7/15.9 MB 4.3 MB/s eta 0:00:02
     --------------------------- ------------ 11.1/15.9 MB 4.4 MB/s eta 0:00:02
     ---------------------------- ----------- 11.3/15.9 MB 4.4 MB/s eta 0:00:02
     ---------------------------- ----------- 11.4/15.9 MB 4.4 MB/s eta 0:00:02
     ----------------------------- ---------- 11.8/15.9 MB 4.4 MB/s eta 0:00:01
     ------------------------------ --------- 12.1/15.9 MB 4.5 MB/s eta 0:00:01
     ------------------------------ --------- 12.2/15.9 MB 4.5 MB/s eta 0:00:01
     ------------------------------- -------- 12.6/15.9 MB 4.6 MB/s eta 0:00:01
     -------------------------------- ------- 13.0/15.9 MB 4.7 MB/s eta 0:00:01
     --------------------------------- ------ 13.2/15.9 MB 4.7 MB/s eta 0:00:01
     --------------------------------- ------ 13.4/15.9 MB 4.7 MB/s eta 0:00:01
     ---------------------------------- ----- 13.8/15.9 MB 4.7 MB/s eta 0:00:01
     ----------------------------------- ---- 14.0/15.9 MB 4.8 MB/s eta 0:00:01
     ----------------------------------- ---- 14.2/15.9 MB 4.8 MB/s eta 0:00:01
     ------------------------------------ --- 14.4/15.9 MB 4.9 MB/s eta 0:00:01
     ------------------------------------- -- 14.8/15.9 MB 5.0 MB/s eta 0:00:01
     ------------------------------------- -- 15.1/15.9 MB 5.0 MB/s eta 0:00:01
     -------------------------------------- - 15.4/15.9 MB 5.1 MB/s eta 0:00:01
     ---------------------------------------  15.8/15.9 MB 5.2 MB/s eta 0:00:01
     ---------------------------------------  15.9/15.9 MB 5.2 MB/s eta 0:00:01
     ---------------------------------------  15.9/15.9 MB 5.2 MB/s eta 0:00:01
     ---------------------------------------  15.9/15.9 MB 5.2 MB/s eta 0:00:01
     ---------------------------------------- 15.9/15.9 MB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pandas in c:\users\acer\anaconda3\lib\site-packages (from pydataset) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas->pydataset) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas->pydataset) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\users\acer\anaconda3\lib\site-packages (from pandas->pydataset) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\acer\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas->pydataset) (1.16.0)
Building wheels for collected packages: pydataset
  Building wheel for pydataset (setup.py): started
  Building wheel for pydataset (setup.py): finished with status 'done'
  Created wheel for pydataset: filename=pydataset-0.2.0-py3-none-any.whl size=15939425 sha256=37f3311170b1bd7846591d9031db2fa8d65a0cc6213dbe0295ab8e6f049e7b56
  Stored in directory: c:\users\acer\appdata\local\pip\cache\wheels\29\93\3f\af54c413cecaac292940342c61882d2a8848674175d0bb0889
Successfully built pydataset
Installing collected packages: pydataset
Successfully installed pydataset-0.2.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
from pydataset import data

initiated datasets repo at: C:\Users\acer\.pydataset/

In [4]:
mtcars=data('mtcars')

In [5]:
type(mtcars)

pandas.core.frame.DataFrame

In [6]:
mtcars

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [11]:
mtcars.groupby(by=['gear']).agg({'mpg':['min','max','mean','count']})

       mpg
       min   max       mean count
gear
3     10.4  21.5  16.106667    15
4     17.8  33.9  24.533333    12
5     15.0  30.4  21.380000     5

In [14]:
mtcars.to_csv('mtcarsas.csv', index=False)

In [17]:
df1=pd.read_csv('mtcars.csv')

NameError: name 'pd' is not defined